# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-26 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_identity_unique_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identity_unique',
            name='First_Name',
            field=models.CharField(default=0, max_length=80, null=True),
        ),
    ]
