# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-26 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20170926_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='identity_unique',
            name='Last_Name',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
